#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
renumberMesh -constant -overwrite

rm -r polyMesh.orig
cp -r ./constant/polyMesh polyMesh.orig

#------------------------------------------------------------------------------
